apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowing-retail.fullname" . }}
  labels:
    app: {{ include "flowing-retail.name" . }}
    chart: {{ include "flowing-retail.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.image.containerPort }}
      name: zeebe
    - port: 26501
      name: zeebe-gateway
  selector:
    app: {{ include "flowing-retail.name" . }}
    release: {{ .Release.Name }}