# Default values for flowing-retail.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: "kafka-java-monitor"
fullnameOverride: ""

image:
  repository: "flowingretail/kafka-java-monitor"
  tag: latest
  pullPolicy: IfNotPresent
  containerPort: 8095

service:
  port: 8095