# Default values for flowing-retail.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: "zeebe"
fullnameOverride: "zeebe"

image:
  repository: "camunda/zeebe"
  tag: 0.12.0
  pullPolicy: IfNotPresent
  containerPort: 26500
