server:
  port: 8083
camunda:
  endpoint: localhost:8080/rest
  worker-topic: Worker-Polling-3
  worker-id: Worker-Polling-3
  worker-schedule: 5000
  worker-max-taks: 3
  worker-thread: 10
  worker-max-queue-size: 10
  worker-time: time3
  worker-multiple-topics: "Worker-Polling-3, Worker-Polling-3B, Worker-Polling-3C"
